### ISSUE TITLE
trailing comma causes error

### ISSUE THREAD

**Issue by cloverrose** [kinbiko/mokku#25]
This Add method has trailing comma in parameters part.
```go
type Calculator interface {
	Add(a int,
		b int,
	) int
}
```

It causes error like this.
```txt
10:30: expected statement, found ')' (and 1 more errors)
Usage:
1. Copy the interface you want to mock
2. Run 'mokku'
3. Paste the mocked implementation that has been written to your clipboard
```

**Comment by kinbiko** [comment]
Ah yes. The package incorrectly assumes that there will be another parameter after the final `,`. As you pointed out, that's not necessarily the case.

Thanks for QA-ing/reporting.
